### ISSUE TITLE
Handle AssertionError as 4xx error (keep showing message even in production / debug false)

### ISSUE THREAD

**Issue by airbinder** [strongloop/strong-error-handler#56]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

As of now, any error object that has no statusCode property will be handled as 5xx error and will not show error message in production.

This is a suggestion to show the message error for Assertion since the error thrown by assert is much used and not-so-simple to add statusCode property (can still be added using try-catch block, but to bothersome)

### Link to sample repo to reproduce issue (if bug)

```javascript
// debug: false
assert.ok(userId, 'userId is required');
```

### Expected result

```json
{
  "error": {
    "statusCode": 500,
    "name": "AssertionError",
    "message": "userId is required"
}
```
### Actual result (if bug)

```json
{
  "error": {
    "statusCode": 500,
    "name": "Internal Server Error"
}
```

### Additional information (Node.js version, LoopBack version, etc)

For information purpose, I know this still can be achieved by try-catch block. But I am suggesting to handle it differently.

```javascript
try {
  assert.ok(userId, 'userId is required');
} catch (error) {
  error.statusCode = 400;
  throw error;
}
```
Many thanks.

**Comment by bajtos** [comment]
If the request is missing a required field (`userId` in your example), then your application should respond with an error code in 4xx range (400 Bad Request, [422 Unprocessable Entity](https://httpstatuses.com/422)), in which case strong-error-handler includes some level of details in the error response.

If the request was valid, but there is a bug in the server application, then there is nothing the client can do even with the additional information from the assertion message. What's worse, your assertion message may leak sensitive details in `expected` and `actual` fields, thus compromising the security of your system. That's why we are not going to treat AssertionError differently from other server-side (5xx) errors.
